openapi: '3.0.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
servers:
  - url: http://localhost:3001/api/v1

paths:
  /user/accounts/{userAccountId}/transactions:
    get:
      tags:
      - User Transactions
      summary: Returns all transactions of a selected month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          schema: 
            type: string
          required: true
        - name: userAccountId
          in: path
          description: user account ID
          required: true
          schema:
            type: string
        - name: month number
          in: query
          description: current month chosen to display
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Transactions data received successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
        '400':
          description: Bad request. Month must be an integer between 1 and 12 and user account ID is a string.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
        '5XX':
          description: Unexpected error.
  /user/accounts/{userAccountId}/transactions/{transactionId}:
    get:
      tags:
      - User Transactions
      summary: Returns a specific transaction in details
      description: Gets data of single transaction details
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        schema: 
            type: string
        required: true
      - name: userAccountId
        in: path
        description: User's account ID
        schema:
          type: integer
        required: true
      - in: path
        name: transactionId
        description: Transaction's ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Transaction's data received successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request. Month must be an integer between 1 and 12 and user account ID is a string.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
        '5XX':
          description: Unexpected error.
    patch:
      tags:
      - User Transactions
      summary: Update and retrns one transaction's data
      description: Modifies data of single transaction details
      parameters:        
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        schema: 
          type: string
        required: true
      - in: path
        name: userAccountId
        description: User's account ID
        required: true
        schema:
          type: integer
      - in: path
        name: transactionId
        description: Transaction's ID
        required: true
        schema:
          type: integer 
      requestBody:
        description: A JSON object containing the modification
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/updateTransactionNotes'
                - $ref: '#/components/schemas/updateTransactionCategory'
      responses:
        '200':
          description: Transaction's data updated successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request. Month must be an integer between 1 and 12 and user account ID is a string.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
        '5XX':
          description: Unexpected error.
    delete:
      tags:
      - User Transactions
      summary: Deletes and returns transaction's data
      description: Deletes notes or category of a transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        schema: 
          type: string
        required: true
      - in: path
        name: userAccountId
        description: User's account ID
        required: true
        schema:
          type: integer
      - in: path
        name: transactionId
        description: User's transaction ID
        required: true
        schema:
          type: integer
      - in: header
        name: deleteData
        required: true
        description: data to delete
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteTransactionInformation'
      responses:
        '200':
          description: Transaction's data deleted successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request. Must enter "notes" or "category" as delete value.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
        '5XX':
          description: Unexpected error.
    
security:
  - ApiKeyAuth: [] 
        
components:
  schemas:
    Transactions:
      type: array
      items:
        $ref: '#/components/schemas/Transaction'
        
    Transaction:
      type: object
      properties:
        transactionsId:
          type: integer
        date:
          type: string
        description:
          type: string
        amount:
          type: number
        currency:
          type: string
        type:
          type: string
        category:
          type: string
        notes:
          type: string
          
    updateTransactionNotes:
      type: object
      properties:
        notes:
          type: string
          
    updateTransactionCategory:
      type: object
      properties:
        category:
          type: string
          
    deleteTransactionInformation:
      type: object
      properties:
        delete:
          type: string
          
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header       
      name: Authorization 
